# Azure DevOps pipeline to deploy SonarQube stack with EC2 and RDS in public subnets across two AZs to AWS
trigger:
  branches:
    include:
      - main
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  awsServiceConnection: 'aws-oidc-federation' # AWS service connection name
  awsRegion: 'us-east-1' # AWS region for deployment
  sonarQubeTemplatePath: '$(System.DefaultWorkingDirectory)/sonarqube-stack-public-only-two-az.yaml' # Path to updated SonarQube CFT
  sonarQubeStackName: 'SonarQubeStackPublicOnly' # Stack name
  vpcId: 'vpc-093582a4fa8c1828e' # Your VPC ID
  publicSubnetId: 'subnet-0601e2496fa2b037b' # Your first public subnet ID (e.g., us-east-1c)
  publicSubnetId2: 'subnet-0d3418b1dd56c8b15' # Replace with your second public subnet ID (e.g., us-east-1a)
  keyName: 'delivery-keypair' # Your EC2 key pair name
  dbPassword: 'MySecurePass123' # Replace with a secure password
  allowedCidrIp: '0.0.0.0/0' # Restrict to Azure DevOps IP range for production

stages:
  - stage: Deploy_SonarQube
    displayName: 'Deploy SonarQube Stack'
    jobs:
      - deployment: DeploySonarQube
        displayName: 'Deploy SonarQube to AWS'
        environment: 'SonarQube'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  displayName: 'Checkout Code'
                - task: AWSShellScript@1
                  displayName: 'Deploy SonarQube CloudFormation Stack'
                  inputs:
                    awsCredentials: '$(awsServiceConnection)'
                    regionName: '$(awsRegion)'
                    scriptType: 'inline'
                    inlineScript: |
                      aws cloudformation deploy \
                        --template-file $(sonarQubeTemplatePath) \
                        --stack-name $(sonarQubeStackName) \
                        --parameter-overrides \
                          VpcId=$(vpcId) \
                          PublicSubnetId=$(publicSubnetId) \
                          PublicSubnetId2=$(publicSubnetId2) \
                          KeyName=$(keyName) \
                          DBPassword=$(dbPassword) \
                          AllowedCidrIp=$(allowedCidrIp) \
                        --capabilities CAPABILITY_NAMED_IAM
                - task: AWSShellScript@1
                  displayName: 'Get SonarQube URL'
                  inputs:
                    awsCredentials: '$(awsServiceConnection)'
                    regionName: '$(awsRegion)'
                    scriptType: 'inline'
                    inlineScript: |
                      SONARQUBE_URL=$(aws cloudformation describe-stacks \
                        --stack-name $(sonarQubeStackName) \
                        --query 'Stacks[0].Outputs[?OutputKey==`SonarQubeURL`].OutputValue' \
                        --output text)
                      echo "##vso[task.setvariable variable=sonarQubeUrl;isOutput=true]$SONARQUBE_URL"
                  name: setSonarQubeUrl
