# Simple Azure DevOps pipeline to validate and deploy an AWS CloudFormation template
trigger:
  branches:
    include:
      - main # Trigger pipeline only on push to main branch
pr: none # Disable PR triggers

pool:
  vmImage: 'ubuntu-latest'

variables:
  awsServiceConnection: 'aws-oidc-federation' # AWS service connection name
  awsRegion: 'us-east-1' # AWS region for deployment
  templatePath: '$(System.DefaultWorkingDirectory)/CloudfrontWithEc2.yaml' # Path to CloudFormation template
  stackName: 'MyEC2CftStack' # Name of the CloudFormation stack

jobs:
  - job: CI
    displayName: 'Validate Template'
    steps:
      - checkout: self
        displayName: 'Checkout Code'
      - task: AWSShellScript@1
        displayName: 'Validate CloudFormation Template'
        inputs:
          awsCredentials: '$(awsServiceConnection)'
          regionName: '$(awsRegion)'
          scriptType: 'inline'
          inlineScript: |
            aws cloudformation validate-template --template-body file://$(templatePath)

  - deployment: CD
    displayName: 'Deploy to AWS'
    dependsOn: CI
    condition: succeeded() # Run only if CI succeeds
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
              displayName: 'Checkout Code'
            - task: AWSShellScript@1
              displayName: 'Deploy CloudFormation Stack'
              inputs:
                awsCredentials: '$(awsServiceConnection)'
                regionName: '$(awsRegion)'
                scriptType: 'inline'
                inlineScript: |
                  aws cloudformation deploy \
                    --template-file $(templatePath) \
                    --stack-name $(stackName) \
                    --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM